/*Problem 2: Even Fibonacci Numbers
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence that do not exceed the nth term, 
find the sum of the even-valued terms.*/

function fiboEvenSum(n) {
  let fiboSequence = [1, 1];
  let res = 0;

  for (let i = 1; i < n; i++) {
    let sum = fiboSequence[i] + fiboSequence[i - 1];
    fiboSequence.push(sum);

    if (sum % 2 == 0) {
      res += sum;
    }
  }

  return res;
}

console.log(fiboEvenSum(18));
